version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-kanri_kanri_1
      APP_PORT: 3000
    
  kanri:
    image: trobonox/kanri:latest
    volumes:
      - kanri_data:/app/data
    restart: unless-stopped

volumes:
  kanri_data:

