version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-openobserve_openobserve_1
      APP_PORT: 5080
    
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    environment:
      ZO_ROOT_USER_EMAIL: admin@openobserve.ai
      ZO_ROOT_USER_PASSWORD: Complexpass#123
      ZO_DATA_DIR: /data
    volumes:
      - openobserve_data:/data
    restart: unless-stopped

volumes:
  openobserve_data:

