version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-superset_superset_1
      APP_PORT: 8088
    
  superset:
    image: apache/superset:latest
    environment:
      SUPERSET_SECRET_KEY: superset_secret_key_change_me
      SUPERSET_CONFIG_PATH: /app/superset_config.py
      DATABASE_DB: superset
      DATABASE_HOST: postgres
      DATABASE_PASSWORD: superset
      DATABASE_USER: superset
      DATABASE_PORT: 5432
      DATABASE_DIALECT: postgresql
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - superset_data:/app/superset_home
      - ./superset_config.py:/app/superset_config.py
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  superset_data:
  postgres_data:
  redis_data: