version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: opensource-keycloak_keycloak_1
      APP_PORT: 8080
    
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    user: "1000:1000"
    init: true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres
    restart: unless-stopped
    command: start-dev

  postgres:
    image: postgres:13-alpine
    user: "1000:1000"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  keycloak_data:
  postgres_data:
