version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-netdata_netdata_1
      APP_PORT: 19999
    
  netdata:
    image: netdata/netdata:latest
    environment:
      NETDATA_CLOUD_URL: http://localhost:19999
    volumes:
      - netdata_config:/etc/netdata
      - netdata_data:/var/lib/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined

volumes:
  netdata_config:
  netdata_data: