version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-pgadmin_pgadmin_1
      APP_PORT: 80  
    
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_logs:/var/log/pgadmin
    restart: unless-stopped

volumes:
  pgadmin_data:
  pgadmin_logs: