version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-twenty_twenty_1
      APP_PORT: 3000
    
  twenty:
    image: twentycrm/twenty:latest
    environment:
      DATABASE_URL: postgres://twenty:twenty@postgres:5432/twenty
      REDIS_URL: redis://redis:6379
      PORT: 3000
      SERVER_URL: http://localhost:3000
    volumes:
      - twenty_data:/app/data
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: twenty
      POSTGRES_USER: twenty
      POSTGRES_PASSWORD: twenty
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  twenty_data:
  postgres_data:

