version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-infisical_infisical_1
      APP_PORT: 8080
    
  infisical:
    image: infisical/infisical:latest
    environment:
      DATABASE_URL: postgres://infisical:infisical@postgres:5432/infisical
      REDIS_URL: redis://redis:6379
      ENCRYPTION_KEY: change-this-encryption-key-32-chars
      JWT_SECRET: change-this-jwt-secret
      SITE_URL: http://localhost:8080
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: infisical
      POSTGRES_USER: infisical
      POSTGRES_PASSWORD: infisical
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres_data:

