version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-opik_opik_1
      APP_PORT: 5173
    
  opik:
    image: cometml/opik:latest
    environment:
      DATABASE_URL: postgres://opik:opik@postgres:5432/opik
    volumes:
      - opik_data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: opik
      POSTGRES_USER: opik
      POSTGRES_PASSWORD: opik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  opik_data:
  postgres_data:

