version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-keystonejs_keystonejs_1
      APP_PORT: 3000
    
  keystonejs:
    image: keystonejs/keystone:latest
    environment:
      DATABASE_URL: postgres://keystone:keystone@postgres:5432/keystone
      SESSION_SECRET: change-this-session-secret
      NODE_ENV: production
    volumes:
      - keystonejs_data:/app/public
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: keystone
      POSTGRES_USER: keystone
      POSTGRES_PASSWORD: keystone
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  keystonejs_data:
  postgres_data:

