version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-languagetool_languagetool_1
      APP_PORT: 8010
    
  languagetool:
    image: erikvl87/languagetool:latest
    environment:
      langtool_languageModel: /ngrams
      Java_Xms: 512m
      Java_Xmx: 1g
    volumes:
      - languagetool_ngrams:/ngrams
    restart: unless-stopped

volumes:
  languagetool_ngrams:

