version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opensource-strapi_strapi_1
      APP_PORT: 1337
    
  strapi:
    image: strapi/strapi:latest
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      JWT_SECRET: change-this-jwt-secret
      ADMIN_JWT_SECRET: change-this-admin-jwt-secret
      APP_KEYS: change-this-app-key-1,change-this-app-key-2
      API_TOKEN_SALT: change-this-api-token-salt
    volumes:
      - strapi_data:/srv/app
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  strapi_data:
  postgres_data:

